// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDphFZz3kIUcvxjrNYDca9ZE1mVOYDWUYI',
    appId: '1:213235388230:web:598e7c8d5bdf3a63a2df47',
    messagingSenderId: '213235388230',
    projectId: 'ebook-e2135',
    authDomain: 'ebook-e2135.firebaseapp.com',
    storageBucket: 'ebook-e2135.appspot.com',
    measurementId: 'G-HW1W3WXMR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCERfXBav6RjUHptn1pGMCfzfi21xVn_NY',
    appId: '1:213235388230:android:d362905cfe78124da2df47',
    messagingSenderId: '213235388230',
    projectId: 'ebook-e2135',
    storageBucket: 'ebook-e2135.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZW5NEhNp-3B6cjqId5Jrrv8jF_4HpeAY',
    appId: '1:213235388230:ios:ec74f2071acef6d7a2df47',
    messagingSenderId: '213235388230',
    projectId: 'ebook-e2135',
    storageBucket: 'ebook-e2135.appspot.com',
    iosBundleId: 'com.example.ebooksFree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZW5NEhNp-3B6cjqId5Jrrv8jF_4HpeAY',
    appId: '1:213235388230:ios:c9c50f5efe98dcb6a2df47',
    messagingSenderId: '213235388230',
    projectId: 'ebook-e2135',
    storageBucket: 'ebook-e2135.appspot.com',
    iosBundleId: 'com.example.ebooksFree.RunnerTests',
  );
}
